### ISSUE TITLE
Build with GHC 8.8

### ISSUE THREAD

**Issue by naushadh** [winterland1989/mysql-haskell#36]
- Using GHC 8.8.1 with stack resolver [nightly-2019-12-23](https://www.stackage.org/nightly-2019-12-23)
  - NOTE: also relaxed version bounds for `memory` and `tls`
- I get a build failure

  ```bash
  $ stack build --resolver nightly
  Selected resolver: nightly-2019-12-23
  Stack has not been tested with GHC versions above 8.6, and using 8.8.1, this may fail
  Stack has not been tested with Cabal versions above 2.4, but version 3.0.0.0 was found, this may fail
  mysql-haskell> build (lib)
  Preprocessing library for mysql-haskell-0.8.4.2..
  Building library for mysql-haskell-0.8.4.2..
  [10 of 14] Compiling Database.MySQL.Protocol.Command

  ~/Dev/open_source/mysql-haskell/Database/MySQL/Protocol/Command.hs:86:36: error:
      • No instance for (MonadFail PutM) arising from a use of ‘fail’
      • In the expression: fail "unsupported command"
        In an equation for ‘putCommand’:
            putCommand _ = fail "unsupported command"
    |
  86 | putCommand _                     = fail "unsupported command"
    |                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^


  --  While building package mysql-haskell-0.8.4.2 using:
        ~/.stack/setup-exe-cache/x86_64-osx/Cabal-simple_mPHDZzAJ_3.0.0.0_ghc-8.8.1 --builddir=.stack-work/dist/x86_64-osx/Cabal-3.0.0.0 build lib:mysql-haskell --ghc-options " -fdiagnostics-color=always"
      Process exited with code: ExitFailure 1
  ```

- I can submit a patch to address this. Could you advice if one these will be acceptable?
  1. Drop `fail` usage by removing `COM_UNSUPPORTED` option thereby eliminating the need to fail. I found 0 code reference from this repo, and across [public github repos](https://github.com/search?l=Haskell&q=%22COM_UNSUPPORTED%22&type=Code).
  2. Use `error`
